"""add candidate summary

Revision ID: 852b7d1967e9
Revises: 70d2bf3478e1
Create Date: 2026-07-22 15:36:58.136755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852b7d1967e9'
down_revision: Union[str, Sequence[str], None] = '70d2bf3478e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'summary')
    # ### end Alembic commands ###
