"""added appropriate indices

Revision ID: 93ef17da3f01
Revises: 852b7d1967e9
Create Date: 2026-07-22 17:05:59.430261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ef17da3f01'
down_revision: Union[str, Sequence[str], None] = '852b7d1967e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scores_candidate_id'), 'scores', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_candidate_id'), table_name='scores')
    # ### end Alembic commands ###
