"""initial migration

Revision ID: aafd75632d8c
Revises: 
Create Date: 2026-07-22 12:49:23.003923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafd75632d8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('internal_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'internal_notes')
    op.drop_column('candidates', 'skills')
    # ### end Alembic commands ###
